const BRANCHES=[
['문정법조타운','송파구','서울특별시 송파구 법원로11길 7'],['문래동','영등포구','서울특별시 영등포구 도림로128길 2'],['역삼중앙','강남구','서울특별시 강남구 역삼로 114'],['온수역','구로구','서울특별시 구로구 부일로 869'],['삼성역','강남구','서울특별시 강남구 테헤란로 625'],['송파','송파구','서울특별시 송파구 송파대로 422'],['노원역','노원구','서울특별시 노원구 노해로 489'],['선유도역','영등포구','서울특별시 영등포구 양평로25길 8'],['문래중앙','영등포구','서울특별시 영등포구 선유로 49'],['명동역','중구','서울특별시 중구 퇴계로 109'],['대림동','영등포구','서울특별시 영등포구 대림로 195'],['당산동','영등포구','서울특별시 영등포구 영신로 220'],['길동','강동구','서울특별시 강동구 천호대로 1139'],['군자역','광진구','서울특별시 광진구 천호대로 579'],['성수희망','성동구','서울특별시 성동구 아차산로 153'],['성수동','성동구','서울특별시 성동구 연무장7길 16'],['워커힐','광진구','서울특별시 광진구 아차산로 635'],['장한평역','성동구','서울특별시 성동구 자동차시장1길 73'],['신당역','중구','서울특별시 중구 퇴계로 439'],['을지6가','중구','서울특별시 중구 장충단로 263'],['청계5가','중구','서울특별시 중구 청계천로 206-1'],['무교','중구','서울특별시 중구 무교로 20'],['남대문시장','중구','서울특별시 중구 남대문로 12'],['서소문','중구','서울특별시 중구 서소문로 120'],['연희동','서대문구','서울특별시 서대문구 연희로 141'],['신촌','서대문구','서울특별시 서대문구 신촌로 67'],['인사동','종로구','서울특별시 종로구 인사동5길 25'],['종로','종로구','서울특별시 종로구 종로 104'],['서울대역','관악구','서울특별시 관악구 남부순환로 1794'],['여의도','영등포구','서울특별시 영등포구 여의나루로 81']
].map((x,i)=>({id:'IBK-'+String(i+1).padStart(3,'0'),name:x[0],district:x[1],address:x[2],type:i%9===0?'개인스마트':'일반/특화점포',phone:'02-'+String(2000+i).padStart(4,'0')+'-'+String(3000+i).padStart(4,'0')}));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={selected:BRANCHES[0],radius:3,impact:'중간',opinions:[]};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function gotoView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#topTitle').textContent=({'dashboard':'BranchFit 의사결정 지원 데모','branches':'점포 운영현황','candidate':'통·폐합 후보 탐색','assessment':'사전영향평가','alternatives':'대체수단 시뮬레이션','opinions':'고객 의견수렴','ai-report':'AI 분석 리포트','post':'사후영향평가','data':'데이터 정의/관리'})[id]||'BranchFit';window.scrollTo({top:0,behavior:'smooth'});if(id==='ai-report')renderReport()}
$$('#nav button').forEach(b=>b.onclick=()=>gotoView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>gotoView(b.dataset.goto));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function metrics(b){const n=Number(b.id.split('-')[1]);return{distance:(1.1+(n*37%91)/10).toFixed(1),channels:2+n%6,overlap:45+n*13%52,eff:38+n*17%59,digital:40+n*19%58}}
function selectBranch(b){state.selected=b;renderDashList();renderMap();renderMini();$('#assessmentBranch').value=b.id;renderAssessment();$('#opinionBranch').value=b.id;$('#selectedTitle').textContent=b.name+' 사전영향평가';$('#dashDistance').textContent=metrics(b).distance+'km';toast(b.name+' 점포를 선택했습니다')}
function renderDashList(){const q=($('#branchSearch').value||'').trim().toLowerCase();const rows=BRANCHES.filter(b=>(b.name+b.district+b.address).toLowerCase().includes(q)).slice(0,14);$('#dashBranchList').innerHTML=rows.map(b=>`<div class="branch-row ${b.id===state.selected.id?'sel':''}" data-branch="${b.id}"><div><strong><span class="dot"></span>${esc(b.name)}</strong><small>${esc(b.district)} · ${esc(b.address)}</small></div><span class="badge b-gray">${esc(b.type)}</span></div>`).join('');$$('[data-branch]').forEach(r=>r.onclick=()=>selectBranch(BRANCHES.find(b=>b.id===r.dataset.branch)))}
$('#branchSearch').oninput=renderDashList;
function renderMap(){const map=$('#mainMap');map.querySelectorAll('.pin,.radius-ring').forEach(n=>n.remove());const pts=BRANCHES.slice(0,20);pts.forEach((b,i)=>{const p=document.createElement('button');p.className='pin '+(b.id===state.selected.id?'selected':'');p.style.left=(10+(i*17%78))+'%';p.style.top=(12+(i*23%70))+'%';p.title=b.name;p.onclick=()=>selectBranch(b);map.appendChild(p)});const r=document.createElement('div');r.className='radius-ring';const size=80+state.radius*16;r.style.width=r.style.height=size+'px';r.style.left='48%';r.style.top='49%';r.style.transform='translate(-50%,-50%)';map.appendChild(r)}
$$('.radiusCtl button').forEach(b=>b.onclick=()=>{state.radius=+b.dataset.r;$$('.radiusCtl button').forEach(x=>x.classList.toggle('active',x===b));renderMap();toast('분석 반경을 '+state.radius+'km로 변경했습니다')});
const assess=[['현황분석','점포 이용고객 현황','고객 수·연령대·취약고객','내부 필요'],['현황분석','점포 이용빈도','방문 고객·방문 횟수','내부 필요'],['현황분석','대면서비스 의존도','대면/비대면 거래 및 평균','내부 필요'],['영향진단','대체점포 거리','점포 좌표·운영 상태','확인'],['영향진단','지역 금융접근성','자·타행·대체채널 위치','확인'],['영향진단','소비자 영향','불편·접근성 종합 검토','일부'],['대체수단','창구 대체율','기존업무/대체업무 매핑','일부'],['대체수단','대체수단 결정','소규모·공동·이동·ATM','확인']];
function renderMini(){const m=metrics(state.selected);$('#miniAssessment').innerHTML=assess.slice(0,5).map((a,i)=>`<div class="assess-row"><div class="num">${i+1}</div><div><b>${a[1]}</b><div class="mini">${i===3?m.distance+'km':i===4?m.channels+'개 채널':a[2]}</div></div><span class="status ${a[3]==='확인'?'ok':a[3]==='일부'?'warn':'unknown'}">${a[3]}</span></div>`).join('')}
$('#dashAiBtn').onclick=()=>{$('#dashAi').innerHTML=`<b>${esc(state.selected.name)}</b>은 최근접 동일은행 대체점포 거리가 데모 기준 <b>${metrics(state.selected).distance}km</b>입니다. 대면서비스 의존도와 취약계층 비율은 내부데이터가 없어 판정하지 않습니다. 현재 단계에서는 <b>추가 확인 필요</b> 상태로 유지하는 것이 적절합니다.`};
function initFilters(){const ds=[...new Set(BRANCHES.map(b=>b.district))].sort(),ts=[...new Set(BRANCHES.map(b=>b.type))];$('#districtFilter').innerHTML='<option value="">전체 자치구</option>'+ds.map(x=>`<option>${x}</option>`).join('');$('#typeFilter').innerHTML='<option value="">전체 유형</option>'+ts.map(x=>`<option>${x}</option>`).join('')}
function renderBranchTable(){const q=($('#tableSearch').value||'').toLowerCase(),d=$('#districtFilter').value,t=$('#typeFilter').value;const rows=BRANCHES.filter(b=>(b.name+b.address+b.district).toLowerCase().includes(q)&&(!d||b.district===d)&&(!t||b.type===t));$('#branchTable').innerHTML=rows.map((b,i)=>`<tr><td><b>${esc(b.name)}</b></td><td>${esc(b.district)}</td><td>${esc(b.type)}</td><td>${esc(b.address)}</td><td>${esc(b.phone)}</td><td><span class="badge ${i%3===0?'b-amber':'b-gray'}">${i%3===0?'검토':'정상'}</span></td><td><button class="btn" data-tablepick="${b.id}">분석</button></td></tr>`).join('');$$('[data-tablepick]').forEach(x=>x.onclick=()=>{selectBranch(BRANCHES.find(b=>b.id===x.dataset.tablepick));gotoView('assessment')})}
['tableSearch','districtFilter','typeFilter'].forEach(id=>$('#'+id).addEventListener('input',renderBranchTable));$('#clearFilter').onclick=()=>{$('#tableSearch').value='';$('#districtFilter').value='';$('#typeFilter').value='';renderBranchTable()};
function score(b){const m=metrics(b),a=+$('[id=rangeOverlap]').value,e=+$('[id=rangeEff]').value,d=+$('[id=rangeDigital]').value,s=a+e+d||1;return Math.round((m.overlap*a+m.eff*e+m.digital*d)/s)}
function renderCandidates(){const arr=BRANCHES.map(b=>({b,m:metrics(b),s:score(b)})).sort((x,y)=>y.s-x.s).slice(0,10);$('#candidateRows').innerHTML=arr.map((x,i)=>`<tr><td><b>${i+1}</b></td><td><b>${esc(x.b.name)}</b></td><td>${x.b.district}</td><td>${x.m.overlap}</td><td>${x.m.eff}</td><td>${x.m.digital}</td><td><b>${x.s}</b><div class="tooltip">BranchFit 데모지수</div></td><td><button class="btn" data-cand="${x.b.id}">사전평가</button></td></tr>`).join('');$('#candidateChart').innerHTML=arr.slice(0,8).map(x=>`<div class="bar" style="height:${x.s}%"><em>${x.s}</em><span>${esc(x.b.name.slice(0,5))}</span></div>`).join('');$$('[data-cand]').forEach(x=>x.onclick=()=>{selectBranch(BRANCHES.find(b=>b.id===x.dataset.cand));gotoView('assessment')})}
[['Overlap','wOverlap'],['Eff','wEff'],['Digital','wDigital']].forEach(([k,o])=>$('#range'+k).oninput=e=>{$('#'+o).textContent=e.target.value;renderCandidates()});
function renderWorkflow(){const s=['점포 운영현황','후보 탐색','사전영향평가','고객·지역 의견','재평가/조정','은행 내부 승인','고객 사전통지','폐점·통합','사후영향평가','보완'];$('#workflow').innerHTML=s.map((x,i)=>`<div class="step ${i<2?'done':i===2?'current':''}"><small>STEP ${String(i+1).padStart(2,'0')}</small><strong>${x}</strong><p>${['데이터 확인','내부/BranchFit 별도','현황→영향→대체수단','의견 수렴','필요 시 반복','사람이 최종 결정','사전 안내','대체수단 운영','실제 영향 점검','추가 조치'][i]}</p></div>`).join('')}
function syncSelects(){const html=BRANCHES.map(b=>`<option value="${b.id}">${esc(b.name)} · ${esc(b.district)}</option>`).join('');$('#assessmentBranch').innerHTML=html;$('#opinionBranch').innerHTML=html}
function renderAssessment(){const b=BRANCHES.find(x=>x.id===$('#assessmentBranch').value)||state.selected;state.selected=b;const m=metrics(b);$('#branchFacts').innerHTML=`<b>${esc(b.name)}</b><br>${esc(b.address)}<br>점포유형: ${esc(b.type)}<br>최근접 자사점포 거리(데모): <b>${m.distance}km</b>`;const vals=['미연동','미연동','미연동',m.distance+' km',m.channels+'개 채널','부분 분석','75% (데모)','운영계획 초안'];$('#assessmentRows').innerHTML=assess.map((a,i)=>`<tr><td>${i+1}</td><td><span class="badge b-blue">${a[0]}</span></td><td><b>${a[1]}</b></td><td>${a[2]}</td><td>${vals[i]}</td><td><span class="status ${a[3]==='확인'?'ok':a[3]==='일부'?'warn':'unknown'}">${a[3]}</span></td><td><button class="btn" data-state="${i}">상태변경</button></td></tr>`).join('');$$('[data-state]').forEach(btn=>btn.onclick=()=>{const st=btn.closest('tr').querySelector('.status');st.className=st.classList.contains('unknown')?'status warn':st.classList.contains('warn')?'status ok':'status unknown';st.textContent=st.classList.contains('ok')?'확인':st.classList.contains('warn')?'담당자 확인':'내부 필요';updateCompletion()});updateCompletion()}
function updateCompletion(){const s=$$('#assessmentRows .status'),ok=s.filter(x=>x.classList.contains('ok')).length,p=Math.round(ok/8*100);$('#completionPct').textContent=p;$('#completionBar').style.width=p+'%';$('#completionText').textContent=`${ok}/8 확인 완료 · 미확보 데이터는 최종판정 보류`}
$('#assessmentBranch').onchange=renderAssessment;$('#runRule').onclick=()=>toast(+metrics(state.selected).distance>10?'거리 10km 초과. 대면서비스 의존도 추가 확인 필요':'10km 초과 조건 아님. 다른 영향요소 별도 검토');
const ALTS=[['소규모점포',18,'높음'],['공동점포',17,'높음'],['창구제휴',13,'중간'],['이동점포',12,'중간'],['디지털점포',9,'중간'],['ATM/STM',5,'낮음']];
function renderAlternatives(){const total=Math.max(1,+$('#serviceTotal').value||20),atm=+$('#atmCount').value;let order=state.impact==='높음'?['소규모점포','공동점포','창구제휴','이동점포']:state.impact==='중간'?['창구제휴','이동점포','소규모점포','ATM/STM']:['ATM/STM','디지털점포','이동점포'];if(atm===0&&!order.includes('ATM/STM'))order.push('ATM/STM');$('#altRecommendations').innerHTML=order.slice(0,4).map((x,i)=>`<div class="assess-row"><div class="num">${i+1}</div><div><b>${x}</b><div class="mini">${x==='ATM/STM'&&atm===0?'반경 1km ATM 0개 → 보완 검토':'영향도 '+state.impact+' 시나리오'}</div></div><span class="status ${i===0?'ok':'warn'}">${i===0?'우선 검토':'대안'}</span></div>`).join('');$('#altTable').innerHTML=ALTS.map(x=>{const r=Math.min(100,Math.round(x[1]/total*100));return`<tr><td><b>${x[0]}</b></td><td>${x[1]} / ${total}</td><td>${r}%<div class="scorebar"><i style="width:${r}%"></i></div></td><td>${x[2]}</td><td><span class="badge ${r>70?'b-green':r>45?'b-amber':'b-gray'}">${r>70?'높음':r>45?'중간':'제한적'}</span></td></tr>`}).join('')}
$$('#impactRadios button').forEach(b=>b.onclick=()=>{state.impact=b.dataset.impact;$$('#impactRadios button').forEach(x=>x.classList.toggle('active',x===b));renderAlternatives()});$('#simulateAlt').onclick=renderAlternatives;
function renderOpinions(){const base=24,n=base+state.opinions.length;$('#opCount').textContent=n;$('#opAvg').textContent=((98+state.opinions.reduce((s,o)=>s+o.score,0))/n).toFixed(1);$('#opChart').innerHTML=[3,5,8,13,11].map((v,i)=>`<div class="bar" style="height:${v*6}%"><em>${v}</em><span>${i+1}점</span></div>`).join('');$('#opinionFeed').innerHTML=state.opinions.slice().reverse().map(o=>`<div class="assess-row" style="grid-template-columns:1fr auto"><div><b>${esc(o.branch)} · ${esc(o.who)}</b><div class="mini" style="margin-top:5px">${esc(o.text||'의견 없음')}</div><div class="mini">선호 대체수단: ${esc(o.alt)}</div></div><span class="badge ${o.score>=4?'b-red':'b-amber'}">불편도 ${o.score}/5</span></div>`).join('')}
$('#submitOpinion').onclick=()=>{const b=BRANCHES.find(x=>x.id===$('#opinionBranch').value);state.opinions.push({branch:b.name,who:$('#respondent').value,score:+$('#inconvenience').value,alt:$('#preferredAlt').value,text:$('#opinionText').value});$('#opinionText').value='';renderOpinions();toast('의견을 데모 세션에 저장했습니다')};
function renderReport(){const b=state.selected,m=metrics(b);$('#reportDoc').innerHTML=`<h3>${esc(b.name)} 점포 의사결정 지원 리포트</h3><div class="meta">BranchFit Demo · 생성일 ${new Date().toLocaleDateString('ko-KR')} · 최종 의사결정은 은행 담당자가 수행</div><section><h4>1. Executive Summary</h4><div class="callout">현재 공개·연동 데이터만으로는 최종 폐점 적정성을 확정할 수 없습니다. 최근접 자사점포 거리는 데모 기준 <b>${m.distance}km</b>이며, 대면서비스 의존도·고객 취약계층 분포·실제 이용현황은 내부데이터 확인이 필요합니다.</div></section><section><h4>2. 확인된 사실</h4><ul><li>대상 점포: ${esc(b.name)} / ${esc(b.district)}</li><li>주소: ${esc(b.address)}</li><li>최근접 자사점포 거리(데모): ${m.distance}km</li><li>반경 ${state.radius}km 대체채널: ${m.channels}개(데모)</li></ul></section><section><h4>3. 추가 확인 필요</h4><ul><li>대면서비스 의존도 및 전체 점포 평균과의 비교</li><li>점포 이용고객 수·이용빈도·고령/취약계층 분포</li><li>고객·지역 의견수렴 결과</li><li>대체수단별 실제 제공업무와 창구 대체율</li></ul></section><section><h4>4. 대체수단 검토안</h4><ul><li>영향도 높음: 소규모점포·공동점포 우선 검토</li><li>영향도 중간: 창구제휴·이동점포 검토</li><li>영향도 낮음: 무인자동화기기 등 보완 검토</li></ul></section><section><h4>5. AI 역할</h4><p>AI는 Rule Engine과 공간분석 결과를 이해 가능한 문장으로 설명하며, 미연동 값을 생성하거나 최종 폐점 결정을 자동 수행하지 않습니다.</p></section>`}
$('#regenReport').onclick=()=>{renderReport();toast('현재 선택 점포 기준으로 리포트를 재생성했습니다')};
const MATRIX=[['대체점포 거리','대상·동일은행 점포 좌표/운영상태','최근접 점포 거리(km)','IBK 점포/지도 API','공식 확인','O','PostGIS'],['대면서비스 의존도','대면·비대면 거래건수/전체평균','점포 의존도 및 평균 비교','은행 내부','공식 확인','X','미연동→UNKNOWN'],['고객/취약계층 현황','고객수·연령·취약고객','비율/분포','은행 내부','공식 언급','X','외부통계 대체 금지'],['점포 이용빈도','내점 고객·방문 빈도','이용빈도','은행 내부','추가확인','X','은행별 산식 확인'],['지역 금융접근성','자·타행·대체채널 위치','주변 접근 가능 채널','공공/은행','공식 확인','△','임의 가중치 없음'],['창구 대체율','기존업무·대체수단 제공업무','업무 대체 범위','은행/공개자료','공식 확인','△','산식 원문 확인'],['대체수단 적정성','대체수단 유형·거리·업무','대체수단 후보','은행/공공','공식 확인','△','Rule→AI 설명'],['고객·지역 의견','설문·민원·지역 의견','불편도/핵심의견','은행 내부','공식 절차','X','재평가 트리거']];
function renderMatrix(){$('#dataMatrix').innerHTML=MATRIX.map(r=>`<tr>${r.map(c=>`<td contenteditable="true">${esc(c)}</td>`).join('')}</tr>`).join('')}
$('#exportData').onclick=()=>{const rows=$$('#dataMatrix tr').map(tr=>[...tr.children].map(td=>td.textContent.trim()));const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='branchfit-data-matrix.json';a.click();URL.revokeObjectURL(a.href)};
$('#quickAnalyze').onclick=()=>gotoView('candidate');$('#sourceBtn').onclick=()=>toast('근거: 금융위 2026 은행 점포폐쇄 대응방안 / 은행연합회 공동절차. 공식·자체 기준을 분리합니다.');$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){$('#tableSearch').value=e.target.value;renderBranchTable();gotoView('branches')}};
function bars(id,vals,labels){$('#'+id).innerHTML=vals.map((v,i)=>`<div class="bar" style="height:${v}%"><em>${v}</em><span>${labels[i]}</span></div>`).join('')}
function init(){renderDashList();renderMap();renderMini();initFilters();syncSelects();renderBranchTable();renderCandidates();renderWorkflow();$('#assessmentBranch').value=state.selected.id;renderAssessment();renderAlternatives();renderOpinions();renderReport();renderMatrix();bars('postChart',[72,68,61,64,70,76,81,84,87,88,86,90],['1주','2주','3주','4주','5주','6주','7주','8주','9주','10주','11주','12주']);$('#opinionBranch').value=state.selected.id}
init();
