const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const branches=[
{id:'IBK-001',name:'역삼중앙',district:'강남구',visits:4280,elderly:18.7,freq:1.12,face:29,score:61},
{id:'IBK-002',name:'삼성역',district:'강남구',visits:3520,elderly:16.8,freq:.91,face:24,score:54},
{id:'IBK-003',name:'명동역',district:'중구',visits:3180,elderly:22.5,freq:.82,face:27,score:67},
{id:'IBK-004',name:'신당역',district:'중구',visits:2410,elderly:24.9,freq:.66,face:35,score:78},
{id:'IBK-005',name:'무교',district:'중구',visits:2890,elderly:20.1,freq:.73,face:31,score:71},
{id:'IBK-006',name:'종로',district:'종로구',visits:2260,elderly:23.8,freq:.64,face:37,score:82},
{id:'IBK-007',name:'인사동',district:'종로구',visits:2640,elderly:22.1,freq:.72,face:34,score:74},
{id:'IBK-008',name:'문래동',district:'영등포구',visits:3370,elderly:19.2,freq:.88,face:28,score:58},
{id:'IBK-009',name:'당산동',district:'영등포구',visits:3010,elderly:18.4,freq:.79,face:26,score:55},
{id:'IBK-010',name:'대림동',district:'영등포구',visits:2180,elderly:21.8,freq:.61,face:33,score:76},
{id:'IBK-011',name:'성수동',district:'성동구',visits:3660,elderly:17.5,freq:.95,face:23,score:49},
{id:'IBK-012',name:'성수희망',district:'성동구',visits:2460,elderly:19.9,freq:.68,face:30,score:69}
];
const districts={강남구:{pop:'564,873명',elderly:'17.8%'},중구:{pop:'131,312명',elderly:'22.4%'},종로구:{pop:'150,215명',elderly:'23.1%'},영등포구:{pop:'397,802명',elderly:'19.6%'},성동구:{pop:'282,211명',elderly:'18.5%'}};
let state={district:'중구',branch:'IBK-004'};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function gotoView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#topTitle').textContent=({dashboard:'대시보드',status:'현황분석',candidates:'후보점포 분석',assessment:'사전영향평가',opinions:'고객 의견 수렴',post:'사후영향평가',data:'데이터 관리'})[id]||'BranchFit';window.scrollTo({top:0,behavior:'smooth'});$('#sidebar').classList.remove('open')}
$$('#nav button').forEach(b=>b.onclick=()=>gotoView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>gotoView(b.dataset.goto));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$('#sourceBtn').onclick=()=>toast('근거자료: 금융위 점포폐쇄 대응방안 · 은행연합회 공동절차 · 공공/내부 데이터');
function fmt(n){return n.toLocaleString('ko-KR')+'명'}
function options(){const ds=Object.keys(districts);const dhtml=ds.map(d=>`<option ${d===state.district?'selected':''}>${d}</option>`).join('');$('#districtSelect').innerHTML=dhtml;$('#candidateDistrict').innerHTML='<option value="전체">전체 자치구</option>'+dhtml;const bhtml=branches.map(b=>`<option value="${b.id}">${b.name} · ${b.district}</option>`).join('');$('#assessmentBranch').innerHTML=bhtml;$('#surveyBranch').innerHTML=bhtml;$('#assessmentBranch').value=state.branch;$('#surveyBranch').value=state.branch}
function renderProgress(){const rows=[['현황분석','완료'],['후보점포 우선순위','완료'],['사전영향평가','진행 중'],['고객 의견 수렴','대기'],['사후영향평가','향후']];$('#progressList').innerHTML=rows.map(r=>`<div><b>${r[0]}</b><span>${r[1]}</span></div>`).join('')}
function districtBranches(d){return branches.filter(b=>b.district===d)}
function renderStatus(){const list=districtBranches(state.district),meta=districts[state.district];$('#districtPop').textContent=meta.pop;$('#districtElderly').textContent=meta.elderly;$('#districtBranches').textContent=list.length+'개';const avg=Math.round(list.reduce((a,b)=>a+b.visits,0)/list.length);const face=Math.round(list.reduce((a,b)=>a+b.face,0)/list.length);$('#mCustomers').textContent=fmt(avg);$('#mVulnerable').textContent=meta.elderly;$('#mFrequency').textContent=(list.reduce((a,b)=>a+b.freq,0)/list.length).toFixed(2)+'배';$('#mFace').textContent=face+'%';$('#statusRows').innerHTML=list.map(b=>`<tr><td><b>${b.name}</b></td><td>${fmt(b.visits)}</td><td>${b.elderly}%</td><td>${b.freq.toFixed(2)}배</td><td>${b.face}%</td></tr>`).join('');const low=[...list].sort((a,b)=>a.visits-b.visits)[0];$('#statusInsight').innerHTML=`<b>${state.district} 현황 요약</b><ul><li>지역 내 ${list.length}개 데모 점포를 비교합니다.</li><li>월평균 방문량이 가장 낮은 점포는 <b>${low.name}</b> (${fmt(low.visits)})입니다.</li><li>이용빈도·고령층·대면서비스 의존도는 단독으로 폐쇄 여부를 결정하는 기준이 아니라, <b>후속 사전영향평가 대상 선별을 위한 현황정보</b>입니다.</li></ul>`}
$('#districtSelect').onchange=e=>{state.district=e.target.value;renderStatus();$('#candidateDistrict').value=state.district;renderCandidates()};
function priority(b){return Math.round((1-b.freq)*45+b.elderly*.9+b.face*.8)}
function renderCandidates(){let list=$('#candidateDistrict').value==='전체'?branches:districtBranches($('#candidateDistrict').value);const sort=$('#candidateSort').value;if(sort==='visit')list=[...list].sort((a,b)=>a.visits-b.visits);else if(sort==='elderly')list=[...list].sort((a,b)=>b.elderly-a.elderly);else list=[...list].sort((a,b)=>priority(b)-priority(a));$('#candidateRows').innerHTML=list.map((b,i)=>`<tr><td><b>${i+1}</b></td><td><b>${b.name}</b><br><small>${b.district}</small></td><td>${fmt(b.visits)}</td><td>${Math.round((b.freq-1)*100)}%</td><td>${b.elderly}%</td><td>${b.face}%</td><td><span class="status ${i<2?'warn':'ok'}">${i<2?'우선 검토':'일반 검토'}</span></td><td><button class="btn" data-assess="${b.id}">사전평가</button></td></tr>`).join('');$$('[data-assess]').forEach(x=>x.onclick=()=>{state.branch=x.dataset.assess;$('#assessmentBranch').value=state.branch;renderAssessment();gotoView('assessment')})}
$('#candidateDistrict').onchange=renderCandidates;
$('#candidateSort').onchange=renderCandidates;
function selected(){return branches.find(b=>b.id===state.branch)||branches[0]}
function impactLevel(score){return score>=75?'높음':score>=55?'중간':'낮음'}
function renderAssessment(){const b=selected();$('#impactScore').textContent=b.score+'점';$('#impactLevel').textContent=impactLevel(b.score);const items=[['점포 이용현황',fmt(b.visits),'확인'],['취약계층 현황',b.elderly+'%','확인'],['점포 이용빈도',b.freq.toFixed(2)+'배','확인'],['대면서비스 의존도',b.face+'%','확인'],['최근접 동일은행 점포','3.2km · 데모','확인'],['고객·지역 의견','아직 수집 전','미수집']];$('#assessmentItems').innerHTML=items.map(x=>`<div class="assessment-item"><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="status ${x[2]==='확인'?'ok':'unknown'}">${x[2]}</span></div>`).join('');$('#aiAssessment').className='ai-summary muted';$('#aiAssessment').textContent='AI 분석 버튼을 누르면 평가결과와 규정 근거를 함께 해석합니다.';$('#directionBox').innerHTML='<b>분석 전</b><p>평가결과를 바탕으로 검토방향을 생성합니다.</p>';renderAlternatives(b)}
$('#assessmentBranch').onchange=e=>{state.branch=e.target.value;renderAssessment()};
function renderAlternatives(b){const high=impactLevel(b.score)==='높음';const alts=high?[['공동·소규모점포','대면서비스 유지 가능성 우선 검토'],['이동점포','지역별 정기 운영 검토'],['인근점포 통합','거리·혼잡도 추가 확인']]:[['인근점포 통합','접근성과 서비스 범위 확인'],['이동점포','필요 시 보완 채널'],['ATM·STM','저영향 업무의 보완 수단']];$('#alternativeCards').innerHTML=alts.map((a,i)=>`<div class="alt"><span class="tag ${i===0?'blue':''}">${i+1}순위 검토</span><b>${a[0]}</b><small>${a[1]}</small></div>`).join('')}
$('#aiAnalyzeBtn').onclick=()=>{const b=selected(),level=impactLevel(b.score);$('#aiAssessment').className='ai-summary';$('#aiAssessment').innerHTML=`<b>${b.name} · 영향도 ${level}</b><p>월평균 이용량은 ${fmt(b.visits)}, 인근점포 대비 이용수준은 ${b.freq.toFixed(2)}배이며 대면서비스 의존도는 ${b.face}%입니다. 관련 사전영향평가 절차상 금융접근성 및 대체수단의 충분성을 함께 검토해야 합니다.</p><p><b>RAG 근거:</b> 금융위 점포폐쇄 대응방안 및 은행연합회 공동절차 관련 문단을 연결하는 데모입니다.</p>`;$('#directionBox').innerHTML=`<b>${level==='높음'?'대체수단 확보 후 신중 검토':level==='중간'?'통합 가능성 + 대체수단 병행 검토':'통합 가능성 검토'}</b><p>AI는 최종 폐쇄를 결정하지 않고, 평가 결과와 규정 근거를 바탕으로 담당자가 확인할 방향을 설명합니다.</p>`;toast('AI 근거 분석을 생성했습니다')};
function bars(el,vals,labels){$(el).innerHTML=vals.map((v,i)=>`<i style="height:${v}%"><span>${labels[i]||''}</span></i>`).join('')}
function surveyTemplate(){const b=selected();return `${b.name} 점포 통·폐합 검토 관련 고객 의견조사\n\n1. 현재 해당 점포를 얼마나 자주 이용하십니까?\n2. 해당 점포가 통합될 경우 예상되는 불편 정도는 어느 정도입니까?\n3. 가장 대체하기 어려운 업무는 무엇입니까?\n4. 이용 가능한 대체수단 중 선호하는 방식은 무엇입니까?\n5. 대체점포까지 이동 가능한 거리는 어느 정도입니까?\n6. 추가로 전달하고 싶은 의견을 자유롭게 작성해 주세요.`}
$('#generateSurvey').onclick=()=>{state.branch=$('#surveyBranch').value;$('#surveyText').value=surveyTemplate();toast('AI 설문 초안을 생성했습니다')};$('#copySurvey').onclick=()=>{navigator.clipboard?.writeText($('#surveyText').value);toast('설문 템플릿을 복사했습니다')};$('#sendSurvey').onclick=()=>{if(!$('#surveyText').value.trim())return toast('먼저 설문을 생성해 주세요');$('#sentCount').textContent='1,420';$('#responseCount').textContent='512';$('#responseRate').textContent='36.1%';toast('데모: 고객 설문 발송을 완료했습니다')};$('#analyzeOpinions').onclick=()=>{$('#opinionSummary').innerHTML='<b>AI 고객의견 분석</b><p>응답자의 68%가 통·폐합 시 불편을 예상했습니다. 자유의견에서는 <b>대체점포 이동거리, 고령층의 디지털 이용 어려움, 대면상담 필요성</b>이 반복적으로 나타났습니다.</p><p>다음 검토에서는 공동점포 또는 대면지원이 가능한 대체수단의 서비스 범위를 우선 확인하는 것이 필요합니다.</p>';toast('고객 응답을 분석했습니다')};
function renderDatasets(){const sets=[['점포 좌표·타행점포','금융결제원/공공 API','CONNECTED'],['인구·고령층 통계','공공데이터','VALIDATED'],['점포 방문수','은행 내부 업로드','UPLOADED'],['대면서비스 의존도','은행 내부 업로드','PARTIAL'],['고객 설문 응답','BranchFit Survey','CONNECTED']];$('#datasetList').innerHTML=sets.map(s=>`<div class="dataset"><div><b>${s[0]}</b><small>${s[1]}</small></div><span class="status ${s[2]==='PARTIAL'?'warn':'ok'}">${s[2]}</span></div>`).join('')}
$('#dataFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#mappingPreview').innerHTML=`<div><b>${f.name}</b> 업로드 감지</div><div>AI 매핑 제안: <b>영업점명 → branch_name</b></div><div>AI 매핑 제안: <b>내점고객 → visit_count</b></div><div>다음 단계: 사용자 확인 → Python ETL → Validation → PostgreSQL</div>`;toast('AI 컬럼 매핑 초안을 생성했습니다')};
function init(){options();renderProgress();renderStatus();$('#candidateDistrict').value=state.district;renderCandidates();renderAssessment();renderDatasets();bars('#surveyBars',[34,46,55,63,71,78],['1일','2일','3일','4일','5일','6일']);bars('#postChart',[58,62,66,69,73,76,80,82,85,87,88,90],['1주','2주','3주','4주','5주','6주','7주','8주','9주','10주','11주','12주'])}
init();