const caseHistory=[
{id:'CASE-2026-014',branch:'신당역',branchId:'IBK-004',district:'중구',stage:'고객 의견 수렴',impact:'높음',state:'설문 진행',updated:'오늘',status:'assessment'},
{id:'CASE-2026-011',branch:'종로',branchId:'IBK-006',district:'종로구',stage:'사후영향평가',impact:'높음',state:'모니터링 필요',updated:'2일 전',status:'post'},
{id:'CASE-2026-009',branch:'대림동',branchId:'IBK-010',district:'영등포구',stage:'후보점포 분석',impact:'-',state:'우선 검토',updated:'5일 전',status:'candidate'},
{id:'CASE-2026-006',branch:'성수희망',branchId:'IBK-012',district:'성동구',stage:'사전영향평가',impact:'중간',state:'검토 중',updated:'7일 전',status:'assessment'}
];
const mapMeta={
'IBK-001':{lat:37.5008,lng:127.0365,status:'normal'},'IBK-002':{lat:37.5088,lng:127.0632,status:'normal'},'IBK-003':{lat:37.5608,lng:126.9864,status:'candidate'},'IBK-004':{lat:37.5656,lng:127.0196,status:'assessment'},'IBK-005':{lat:37.5671,lng:126.9794,status:'normal'},'IBK-006':{lat:37.5704,lng:126.9921,status:'post'},'IBK-007':{lat:37.5730,lng:126.9852,status:'assessment'},'IBK-008':{lat:37.5175,lng:126.8959,status:'normal'},'IBK-009':{lat:37.5348,lng:126.9027,status:'normal'},'IBK-010':{lat:37.4930,lng:126.8967,status:'candidate'},'IBK-011':{lat:37.5446,lng:127.0558,status:'normal'},'IBK-012':{lat:37.5440,lng:127.0647,status:'assessment'}
};
let analysisMap, mapLayerGroup, activeMapFilter='all';
const mapColors={normal:'#1769e0',candidate:'#f59f00',assessment:'#e85976',post:'#0ca678'};
function stageLabel(status){return({normal:'일반 운영',candidate:'검토 후보',assessment:'사전영향평가',post:'사후 모니터링'})[status]||status}
function renderCaseHistory(){const el=document.querySelector('#recentCases');if(!el)return;el.innerHTML=caseHistory.map(c=>`<div class="case-row" data-case-branch="${c.branchId}"><div class="case-row-top"><b>${c.branch} · ${c.district}</b><span class="stage-badge">${c.stage}</span></div><small>${c.id} · 최근 업데이트 ${c.updated}</small><div class="case-meta"><span class="tag ${c.impact==='높음'?'amber':''}">영향도 ${c.impact}</span><span class="tag">${c.state}</span></div></div>`).join('');document.querySelectorAll('[data-case-branch]').forEach(el=>el.onclick=()=>{const id=el.dataset.caseBranch;if(typeof state!=='undefined'){state.branch=id}const select=document.querySelector('#assessmentBranch');if(select){select.value=id;if(typeof renderAssessment==='function')renderAssessment()}if(typeof gotoView==='function')gotoView('assessment')})}
function renderAlerts(){const el=document.querySelector('#dashboardAlerts');if(!el)return;el.innerHTML='<div class="alert-item red"><b>사후 모니터링</b><br>종로점 대체점포 방문량·민원이 함께 증가했습니다.</div><div class="alert-item"><b>고객 의견</b><br>신당역점 설문에서 대체점포 이동거리 관련 의견이 집중되고 있습니다.</div><div class="alert-item"><b>데이터 확인</b><br>2개 분석 Case에서 대체수단 서비스 범위 확인이 필요합니다.</div>'}
function initMap(){if(!window.L||!document.querySelector('#analysisMap'))return;analysisMap=L.map('analysisMap',{zoomControl:true,scrollWheelZoom:false}).setView([37.555,126.997],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(analysisMap);mapLayerGroup=L.layerGroup().addTo(analysisMap);renderMapMarkers();setTimeout(()=>analysisMap.invalidateSize(),200)}
function renderMapMarkers(){if(!mapLayerGroup)return;mapLayerGroup.clearLayers();branches.forEach(b=>{const m=mapMeta[b.id];if(!m||(activeMapFilter!=='all'&&m.status!==activeMapFilter))return;const marker=L.circleMarker([m.lat,m.lng],{radius:8,color:'#fff',weight:2,fillColor:mapColors[m.status],fillOpacity:1}).addTo(mapLayerGroup);marker.bindPopup(`<div class="popup-card"><b>IBK ${b.name}</b><small>${b.district}</small><div class="popup-stage" style="color:${mapColors[m.status]}">${stageLabel(m.status)}</div><small>월평균 방문 ${b.visits.toLocaleString()}명 · 고령층 ${b.elderly}%</small><button data-popup-branch="${b.id}">분석 상세보기</button></div>`);marker.on('popupopen',()=>setTimeout(()=>{const btn=document.querySelector(`[data-popup-branch="${b.id}"]`);if(btn)btn.onclick=()=>{state.branch=b.id;document.querySelector('#assessmentBranch').value=b.id;renderAssessment();gotoView('assessment')}},0))})}
function bindMapFilters(){document.querySelectorAll('[data-map-filter]').forEach(btn=>btn.onclick=()=>{activeMapFilter=btn.dataset.mapFilter;document.querySelectorAll('[data-map-filter]').forEach(x=>x.classList.toggle('active',x===btn));renderMapMarkers()})}
function bindPostAI(){const btn=document.querySelector('#postAiBtn');if(!btn)return;btn.onclick=()=>{const box=document.querySelector('#postAiSummary');box.classList.remove('muted');box.innerHTML='<b>AI 사후영향 분석</b><p>폐점 이후 대체점포 방문량은 38%, 평균 대기시간은 7분 증가했고 월 민원은 12건에서 34건으로 늘었습니다. 공동점포 이용률은 61%로 운영 중이지만, 기업대출 상담 업무는 현재 대체되지 않아 서비스 공백이 확인됩니다.</p><p><b>추가 검토:</b> 통합점포 혼잡 완화, 기업대출 상담 대체채널 확보, 고령고객 접근성 재확인, 4주 후 VOC 재모니터링.</p>';toast('사후영향 분석을 생성했습니다')}}
function bindPostCase(){const sel=document.querySelector('#postCaseSelect');if(!sel)return;sel.innerHTML=caseHistory.filter(c=>c.status==='post').map(c=>`<option value="${c.id}">${c.branch} · ${c.id}</option>`).join('')}
function renderCaseStorage(){const el=document.querySelector('#caseHistoryRows');if(!el)return;el.innerHTML=caseHistory.map(c=>`<tr><td><b>${c.id}</b><small>${c.branch} · ${c.district}</small></td><td>${c.stage}</td><td>${c.impact}</td><td>${c.state}</td><td>${c.updated}</td></tr>`).join('')}
window.addEventListener('load',()=>{renderCaseHistory();renderAlerts();bindMapFilters();initMap();bindPostAI();bindPostCase();renderCaseStorage()});